package br.com.nutriplus.dto.response;

import br.com.nutriplus.domain.enums.ActivityLevel;
import br.com.nutriplus.domain.enums.AgentPersona;
import br.com.nutriplus.domain.enums.CalculationMethod;
import br.com.nutriplus.domain.enums.ChewingDifficulty;
import br.com.nutriplus.domain.enums.DietaryPreference;
import br.com.nutriplus.domain.enums.FoodBudgetLevel;
import br.com.nutriplus.domain.enums.Goal;
import br.com.nutriplus.domain.enums.HungerPattern;
import br.com.nutriplus.domain.enums.NutritionMode;
import br.com.nutriplus.domain.enums.Restriction;
import br.com.nutriplus.domain.enums.Sex;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

public record NutritionProfileResponse(
        Long id,
        Integer age,
        LocalDate birthDate,
        String stateCode,
        String city,
        ChewingDifficulty chewingDifficulty,
        boolean seniorWeightLossAck,
        String lifeStage,
        Sex sex,
        BigDecimal heightCm,
        BigDecimal currentWeightKg,
        BigDecimal targetWeightKg,
        Integer goalTargetWeeks,
        Goal goal,
        ActivityLevel activityLevel,
        DietaryPreference dietaryPreference,
        Restriction restriction,
        AgentPersona agentPersona,
        String foodLikes,
        String foodDislikes,
        String mealNotes,
        boolean eatsBreakfast,
        boolean eatsLunch,
        boolean eatsAfternoonSnack,
        boolean eatsDinner,
        boolean openToRoutineAdjustment,
        HungerPattern hungerPattern,
        NutritionMode nutritionMode,
        List<String> freeExtras,
        FoodBudgetLevel foodBudgetLevel,
        CalculationMethod calculationMethod,
        BigDecimal bodyFatPercent,
        BigDecimal leanMassKg,
        BigDecimal muscleMassKg,
        BigDecimal bmrKcal,
        BigDecimal tdeeKcal,
        BigDecimal targetCalories,
        BigDecimal targetProteinG,
        BigDecimal targetCarbsG,
        BigDecimal targetFatG,
        BigDecimal trainingDailyExtraKcal,
        String paceWarning,
        BigDecimal estimatedWeeklyRateKg,
        LocalDateTime updatedAt,
        boolean athleteModeEnabled,
        String wakeTime,
        String sleepTime,
        String healthConditions,
        String medications,
        String allergies,
        String healthNotes,
        String pregnancyStatus,
        boolean eatingDisorderRisk,
        boolean severeRenalRestriction,
        boolean aiPlanEligible,
        String aiPlanIneligibleReason,
        HealthIndicatorResponse bmiSnapshot,
        SubscriptionStatusResponse subscriptionStatus
) {
}
