package br.com.nutriplus.dto.response;

import br.com.nutriplus.domain.enums.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record NutritionProfileResponse(
        Long id,
        Integer age,
        LocalDate birthDate,
        String stateCode,
        String city,
        ChewingDifficulty chewingDifficulty,
        boolean seniorWeightLossAck,
        String lifeStage,
        Sex sex,
        BigDecimal heightCm,
        BigDecimal currentWeightKg,
        BigDecimal targetWeightKg,
        Integer goalTargetWeeks,
        Goal goal,
        ActivityLevel activityLevel,
        DietaryPreference dietaryPreference,
        Restriction restriction,
        AgentPersona agentPersona,
        String foodLikes,
        String foodDislikes,
        String mealNotes,
        boolean eatsBreakfast,
        boolean eatsLunch,
        boolean eatsAfternoonSnack,
        boolean eatsDinner,
        boolean openToRoutineAdjustment,
        java.util.List<String> freeExtras,
        FoodBudgetLevel foodBudgetLevel,
        CalculationMethod calculationMethod,
        BigDecimal bodyFatPercent,
        BigDecimal leanMassKg,
        BigDecimal muscleMassKg,
        BigDecimal bmrKcal,
        BigDecimal tdeeKcal,
        BigDecimal targetCalories,
        BigDecimal targetProteinG,
        BigDecimal targetCarbsG,
        BigDecimal targetFatG,
        BigDecimal trainingDailyExtraKcal,
        LocalDateTime updatedAt,
        boolean athleteModeEnabled,
        String wakeTime,
        String sleepTime,
        String healthConditions,
        String medications,
        String allergies,
        String healthNotes,
        HealthIndicatorResponse bmiSnapshot
) {
}
